HW#1 - Izukova Darya
js-training-sep-2020/hw-1 pull request #7
Opened 2020-09-20 17:34 UTC by izukovdariy

Сделана первая часть домашнего задания - разметка, заготовлена графика и немного стилей

2020-09-25 18:59 UTC, Katerina-cloud requested changes

2020-09-25 18:59 UTC, Katerina-cloud commented on scss/_main.scss
> +  background: url("../img/bg-widget.png") no-repeat center 100%;
I think that the backgroud should cover the whole screen. It can be done by adding the following styles to the .widget 
```
background-position: center;
background-size: cover;
```
deleting `width: 800px;`

and adding to the .widget__container 
`margin: auto;`

2020-09-25 18:59 UTC, Katerina-cloud commented on scss/_main.scss
> +    background-image: url("../img/bg-container.png");
There is the possibility to add shadow with `box-shadow: 0 0 60px #000000;`
To make it work, remove the padding from .container and add it to the .widget.

2020-09-25 18:59 UTC, Katerina-cloud commented on scss/_main.scss
> +    background-image: url("../img/bg-container.png");
There is the possibility to add shadow using `box-shadow: 0 0 60px #000000;` instead of the image.
To make it work, remove the padding from the .container and add it to the .widget.

2020-09-25 18:59 UTC, Katerina-cloud commented on index.html
> +              <div class="widget__day__title">mon</div>
An element is always part of a block, not another element. This means that the names of elements cannot follow such hierarchy of the form block__elem1__elem2.

https://ru.bem.info/methodology/quick-start/

2020-09-25 18:59 UTC, Katerina-cloud commented on scss/_config.scss
> +$name-colors: (
The widget looks great in all browsers!

2020-09-25 18:59 UTC, Katerina-cloud commented on index.html
> +    <section class="widget">
The code is readable, good job!

2020-09-28 11:21 UTC, izukovdariy commented on index.html
> +    <section class="widget">
Thank you for the feedback, it really helped me to understand my mistakes and i hope new commits are correct.

2020-10-06 14:54 UTC, Katerina-cloud approved these changes

2025-01-15 15:21 UTC, closed without merging